
import { Word } from './types';

export const INITIAL_WORDS: Word[] = [
  // --- ANIMALS ---
  { italian: 'gatto', english: 'cat', category: 'animals', difficulty: 'easy', hint: 'Fa le fusa e dice miao.' },
  { italian: 'cane', english: 'dog', category: 'animals', difficulty: 'easy', hint: 'Il migliore amico dell\'uomo.' },
  { italian: 'orso', english: 'bear', category: 'animals', difficulty: 'easy', hint: 'Un grande animale che va in letargo.' },
  { italian: 'pesce', english: 'fish', category: 'animals', difficulty: 'easy', hint: 'Vive nell\'acqua e nuota.' },
  { italian: 'mucca', english: 'cow', category: 'animals', difficulty: 'easy', hint: 'Ci dà il latte e fa muu.' },
  { italian: 'maiale', english: 'pig', category: 'animals', difficulty: 'easy', hint: 'È rosa e ama il fango.' },
  { italian: 'topo', english: 'mouse', category: 'animals', difficulty: 'easy', hint: 'Piccolo e ama il formaggio.' },
  { italian: 'farfalla', english: 'butterfly', category: 'animals', difficulty: 'medium', hint: 'Ha ali colorate e vola sui fiori.' },
  { italian: 'coniglio', english: 'rabbit', category: 'animals', difficulty: 'medium', hint: 'Ha lunghe orecchie e ama le carote.' },
  { italian: 'tartaruga', english: 'turtle', category: 'animals', difficulty: 'medium', hint: 'Cammina piano e ha un guscio duro.' },
  { italian: 'giraffa', english: 'giraffe', category: 'animals', difficulty: 'medium', hint: 'Ha un collo lunghissimo.' },
  { italian: 'elefante', english: 'elephant', category: 'animals', difficulty: 'medium', hint: 'È grandissimo e ha una proboscide.' },
  { italian: 'scimmia', english: 'monkey', category: 'animals', difficulty: 'medium', hint: 'Le piace saltare sugli alberi e mangiare banane.' },
  { italian: 'leone', english: 'lion', category: 'animals', difficulty: 'medium', hint: 'Il re della foresta con la criniera.' },
  { italian: 'tigre', english: 'tiger', category: 'animals', difficulty: 'medium', hint: 'Grande gatto a strisce arancioni e nere.' },
  { italian: 'cavallo', english: 'horse', category: 'animals', difficulty: 'medium', hint: 'Si può cavalcare e galoppa.' },
  { italian: 'pecora', english: 'sheep', category: 'animals', difficulty: 'medium', hint: 'Soffice e ci dà la lana.' },
  { italian: 'gallina', english: 'hen', category: 'animals', difficulty: 'medium', hint: 'Fa le uova nel pollaio.' },
  { italian: 'anatra', english: 'duck', category: 'animals', difficulty: 'medium', hint: 'Fa qua qua e nuota nel lago.' },
  { italian: 'coccodrillo', english: 'crocodile', category: 'animals', difficulty: 'hard', hint: 'Rettile pericoloso con tanti denti.' },
  { italian: 'ippopotamo', english: 'hippopotamus', category: 'animals', difficulty: 'hard', hint: 'Grande animale africano che ama l\'acqua.' },
  { italian: 'pipistrello', english: 'bat', category: 'animals', difficulty: 'hard', hint: 'Dorme a testa in giù e vola di notte.' },
  { italian: 'scoiattolo', english: 'squirrel', category: 'animals', difficulty: 'hard', hint: 'Raccoglie ghiande e ha una coda folta.' },
  { italian: 'lucertola', english: 'lizard', category: 'animals', difficulty: 'hard', hint: 'Piccolo rettile che ama il sole.' },
  { italian: 'rondine', english: 'swallow', category: 'animals', difficulty: 'hard', hint: 'Uccello che annuncia la primavera.' },
  { italian: 'squalo', english: 'shark', category: 'animals', difficulty: 'hard', hint: 'Pesce grande con pinna e tanti denti.' },
  { italian: 'dinosauro', english: 'dinosaur', category: 'animals', difficulty: 'hard', hint: 'Animale gigantesco vissuto tantissimo tempo fa.' },
  { italian: 'pinguino', english: 'penguin', category: 'animals', difficulty: 'hard', hint: 'Uccello che non vola ma nuota nel ghiaccio.' },
  { italian: 'canguro', english: 'kangaroo', category: 'animals', difficulty: 'hard', hint: 'Salta e ha un marsupio per il cucciolo.' },

  // --- FOOD ---
  { italian: 'pane', english: 'bread', category: 'food', difficulty: 'easy', hint: 'Si mangia a tavola, buono col formaggio.' },
  { italian: 'latte', english: 'milk', category: 'food', difficulty: 'easy', hint: 'Bevanda bianca che viene dalla mucca.' },
  { italian: 'mela', english: 'apple', category: 'food', difficulty: 'easy', hint: 'Un frutto rosso o verde, croccante.' },
  { italian: 'pizza', english: 'pizza', category: 'food', difficulty: 'easy', hint: 'Piatto italiano famoso rotondo.' },
  { italian: 'pasta', english: 'pasta', category: 'food', difficulty: 'easy', hint: 'Spaghetti o penne.' },
  { italian: 'gelato', english: 'ice cream', category: 'food', difficulty: 'easy', hint: 'È freddo, dolce e buono d\'estate.' },
  { italian: 'acqua', english: 'water', category: 'food', difficulty: 'easy', hint: 'Si beve quando si ha sete.' },
  { italian: 'torta', english: 'cake', category: 'food', difficulty: 'easy', hint: 'Si mangia ai compleanni con le candeline.' },
  { italian: 'formaggio', english: 'cheese', category: 'food', difficulty: 'medium', hint: 'Piace molto ai topolini.' },
  { italian: 'pomodoro', english: 'tomato', category: 'food', difficulty: 'medium', hint: 'È rosso e si usa per il sugo.' },
  { italian: 'banana', english: 'banana', category: 'food', difficulty: 'medium', hint: 'Un frutto giallo e curvo.' },
  { italian: 'arancia', english: 'orange', category: 'food', difficulty: 'medium', hint: 'Un agrume rotondo e succoso.' },
  { italian: 'uova', english: 'eggs', category: 'food', difficulty: 'medium', hint: 'Le fa la gallina.' },
  { italian: 'carne', english: 'meat', category: 'food', difficulty: 'medium', hint: 'Bistecca o pollo.' },
  { italian: 'frutta', english: 'fruit', category: 'food', difficulty: 'medium', hint: 'Mele, pere e banane.' },
  { italian: 'limone', english: 'lemon', category: 'food', difficulty: 'medium', hint: 'Giallo e molto aspro.' },
  { italian: 'carota', english: 'carrot', category: 'food', difficulty: 'medium', hint: 'Arancione e piace ai conigli.' },
  { italian: 'cioccolato', english: 'chocolate', category: 'food', difficulty: 'hard', hint: 'Dolce scuro fatto con il cacao.' },
  { italian: 'fragola', english: 'strawberry', category: 'food', difficulty: 'hard', hint: 'Frutto rosso piccolo con i semini fuori.' },
  { italian: 'melanzana', english: 'eggplant', category: 'food', difficulty: 'hard', hint: 'Verdura viola scuro.' },
  { italian: 'biscotto', english: 'cookie', category: 'food', difficulty: 'hard', hint: 'Dolce croccante da inzuppare nel latte.' },
  { italian: 'zucchero', english: 'sugar', category: 'food', difficulty: 'hard', hint: 'Bianco e rende le cose dolci.' },

  // --- OBJECTS / HOME ---
  { italian: 'luna', english: 'moon', category: 'objects', difficulty: 'easy', hint: 'Illumina la notte nel cielo.' },
  { italian: 'sole', english: 'sun', category: 'objects', difficulty: 'easy', hint: 'Ci riscalda e ci dà luce.' },
  { italian: 'casa', english: 'house', category: 'objects', difficulty: 'easy', hint: 'Dove vivi con la tua famiglia.' },
  { italian: 'letto', english: 'bed', category: 'objects', difficulty: 'easy', hint: 'Ci dormi la notte.' },
  { italian: 'porta', english: 'door', category: 'objects', difficulty: 'easy', hint: 'Si apre per entrare in una stanza.' },
  { italian: 'palla', english: 'ball', category: 'objects', difficulty: 'easy', hint: 'Rimbalza e ci giochi.' },
  { italian: 'tavolo', english: 'table', category: 'objects', difficulty: 'medium', hint: 'Ci mangi sopra o ci fai i compiti.' },
  { italian: 'sedia', english: 'chair', category: 'objects', difficulty: 'medium', hint: 'Ti serve per sederti.' },
  { italian: 'finestra', english: 'window', category: 'objects', difficulty: 'medium', hint: 'La apri per far entrare aria e luce.' },
  { italian: 'matita', english: 'pencil', category: 'objects', difficulty: 'medium', hint: 'La usi per scrivere o disegnare.' },
  { italian: 'libro', english: 'book', category: 'objects', difficulty: 'medium', hint: 'Lo leggi per imparare storie nuove.' },
  { italian: 'zaino', english: 'backpack', category: 'objects', difficulty: 'medium', hint: 'Lo metti in spalla per andare a scuola.' },
  { italian: 'chiave', english: 'key', category: 'objects', difficulty: 'medium', hint: 'Serve per aprire la porta.' },
  { italian: 'divano', english: 'sofa', category: 'objects', difficulty: 'medium', hint: 'Comodo per sedersi in salotto.' },
  { italian: 'piatto', english: 'plate', category: 'objects', difficulty: 'medium', hint: 'Ci metti sopra il cibo per mangiare.' },
  { italian: 'meraviglia', english: 'wonder', category: 'objects', difficulty: 'hard', hint: 'Qualcosa di bellissimo che ti stupisce.' },
  { italian: 'avventura', english: 'adventure', category: 'objects', difficulty: 'hard', hint: 'Un viaggio emozionante e rischioso.' },
  { italian: 'biblioteca', english: 'library', category: 'objects', difficulty: 'hard', hint: 'Posto pieno di libri da leggere.' },
  { italian: 'specchio', english: 'mirror', category: 'objects', difficulty: 'hard', hint: 'Ti riflette l\'immagine.' },
  { italian: 'orologio', english: 'clock', category: 'objects', difficulty: 'hard', hint: 'Ti dice che ore sono.' },
  { italian: 'telefono', english: 'telephone', category: 'objects', difficulty: 'hard', hint: 'Serve per chiamare le persone lontane.' },

  // --- COLORS ---
  { italian: 'rosso', english: 'red', category: 'colors', difficulty: 'easy', hint: 'Il colore del cuore e delle fragole.' },
  { italian: 'blu', english: 'blue', category: 'colors', difficulty: 'easy', hint: 'Il colore del cielo e del mare.' },
  { italian: 'nero', english: 'black', category: 'colors', difficulty: 'easy', hint: 'Il colore della notte buia.' },
  { italian: 'bianco', english: 'white', category: 'colors', difficulty: 'easy', hint: 'Il colore della neve.' },
  { italian: 'rosa', english: 'pink', category: 'colors', difficulty: 'easy', hint: 'Il colore dei maialini.' },
  { italian: 'arancione', english: 'orange', category: 'colors', difficulty: 'medium', hint: 'Il colore delle carote e delle arance.' },
  { italian: 'giallo', english: 'yellow', category: 'colors', difficulty: 'medium', hint: 'Il colore del sole e dei limoni.' },
  { italian: 'verde', english: 'green', category: 'colors', difficulty: 'medium', hint: 'Il colore dell\'erba e delle foglie.' },
  { italian: 'viola', english: 'purple', category: 'colors', difficulty: 'medium', hint: 'Il colore dell\'uva e delle melanzane.' },
  { italian: 'grigio', english: 'grey', category: 'colors', difficulty: 'medium', hint: 'Il colore delle nuvole di pioggia.' },
  { italian: 'marrone', english: 'brown', category: 'colors', difficulty: 'medium', hint: 'Il colore del cioccolato e della terra.' },
  { italian: 'celeste', english: 'light blue', category: 'colors', difficulty: 'hard', hint: 'Il colore del cielo sereno.' },

  // --- PEOPLE ---
  { italian: 'mamma', english: 'mom', category: 'people', difficulty: 'easy', hint: 'La donna più importante della famiglia.' },
  { italian: 'papa', english: 'dad', category: 'people', difficulty: 'easy', hint: 'L\'uomo più importante della famiglia.' },
  { italian: 'nonna', english: 'grandma', category: 'people', difficulty: 'easy', hint: 'La mamma della tua mamma o del tuo papà.' },
  { italian: 'nonno', english: 'grandpa', category: 'people', difficulty: 'easy', hint: 'Il papà del tuo papà o della tua mamma.' },
  { italian: 'famiglia', english: 'family', category: 'people', difficulty: 'medium', hint: 'Mamma, papà, fratelli e sorelle.' },
  { italian: 'amico', english: 'friend', category: 'people', difficulty: 'medium', hint: 'Qualcuno con cui ti piace giocare.' },
  { italian: 'maestra', english: 'teacher', category: 'people', difficulty: 'medium', hint: 'Ti insegna cose nuove a scuola.' },
  { italian: 'bambino', english: 'child', category: 'people', difficulty: 'medium', hint: 'Una persona piccola, non un adulto.' },
  { italian: 'fratello', english: 'brother', category: 'people', difficulty: 'medium', hint: 'Il figlio maschio dei tuoi genitori.' },
  { italian: 'sorella', english: 'sister', category: 'people', difficulty: 'medium', hint: 'La figlia femmina dei tuoi genitori.' },
  { italian: 'insegnante', english: 'teacher', category: 'people', difficulty: 'hard', hint: 'Sinonimo di maestro o professore.' },
  { italian: 'compagno', english: 'companion', category: 'people', difficulty: 'hard', hint: 'Qualcuno che sta con te, un amico di scuola.' },
  { italian: 'dottore', english: 'doctor', category: 'people', difficulty: 'hard', hint: 'Ti cura quando sei malato.' },
  { italian: 'poliziotto', english: 'policeman', category: 'people', difficulty: 'hard', hint: 'Aiuta a mantenere l\'ordine.' },

  // --- VERBS ---
  { italian: 'ridere', english: 'to laugh', category: 'verbs', difficulty: 'easy', hint: 'Lo fai quando sei felice o senti una barzelletta.' },
  { italian: 'bere', english: 'to drink', category: 'verbs', difficulty: 'easy', hint: 'Mandare giù acqua o succo.' },
  { italian: 'correre', english: 'to run', category: 'verbs', difficulty: 'medium', hint: 'Andare molto veloce con le gambe.' },
  { italian: 'saltare', english: 'to jump', category: 'verbs', difficulty: 'medium', hint: 'Staccarsi da terra con un balzo.' },
  { italian: 'mangiare', english: 'to eat', category: 'verbs', difficulty: 'medium', hint: 'Mettere cibo in bocca.' },
  { italian: 'dormire', english: 'to sleep', category: 'verbs', difficulty: 'medium', hint: 'Lo fai nel letto di notte.' },
  { italian: 'giocare', english: 'to play', category: 'verbs', difficulty: 'medium', hint: 'Divertirsi con i giochi o gli amici.' },
  { italian: 'cantare', english: 'to sing', category: 'verbs', difficulty: 'medium', hint: 'Fare musica con la voce.' },
  { italian: 'ballare', english: 'to dance', category: 'verbs', difficulty: 'medium', hint: 'Muoversi a tempo di musica.' },
  { italian: 'leggere', english: 'to read', category: 'verbs', difficulty: 'medium', hint: 'Guardare le parole in un libro.' },
  { italian: 'camminare', english: 'to walk', category: 'verbs', difficulty: 'hard', hint: 'Muoversi usando le gambe, ma piano.' },
  { italian: 'raccontare', english: 'to tell', category: 'verbs', difficulty: 'hard', hint: 'Dire una storia a qualcuno.' },
  { italian: 'disegnare', english: 'to draw', category: 'verbs', difficulty: 'hard', hint: 'Fare figure con la matita o i pennarelli.' },
  { italian: 'scrivere', english: 'to write', category: 'verbs', difficulty: 'hard', hint: 'Usare la penna per mettere parole su carta.' },
  { italian: 'imparare', english: 'to learn', category: 'verbs', difficulty: 'hard', hint: 'Capire cose nuove a scuola.' },
  { italian: 'ascoltare', english: 'to listen', category: 'verbs', difficulty: 'hard', hint: 'Usare le orecchie per sentire.' },
  { italian: 'guardare', english: 'to watch', category: 'verbs', difficulty: 'hard', hint: 'Usare gli occhi per vedere qualcosa.' },

  // --- NUMBERS (New) ---
  { italian: 'uno', english: 'one', category: 'numbers', difficulty: 'easy', hint: 'Il primo numero dopo lo zero.' },
  { italian: 'due', english: 'two', category: 'numbers', difficulty: 'easy', hint: 'Una coppia, come le scarpe.' },
  { italian: 'tre', english: 'three', category: 'numbers', difficulty: 'easy', hint: 'Il numero dei porcellini della fiaba.' },
  { italian: 'quattro', english: 'four', category: 'numbers', difficulty: 'easy', hint: 'Le zampe del cane.' },
  { italian: 'cinque', english: 'five', category: 'numbers', difficulty: 'easy', hint: 'Le dita di una mano.' },
  { italian: 'sei', english: 'six', category: 'numbers', difficulty: 'easy', hint: 'Mezza dozzina.' },
  { italian: 'sette', english: 'seven', category: 'numbers', difficulty: 'easy', hint: 'I giorni della settimana.' },
  { italian: 'otto', english: 'eight', category: 'numbers', difficulty: 'easy', hint: 'Le zampe del ragno.' },
  { italian: 'nove', english: 'nine', category: 'numbers', difficulty: 'easy', hint: 'Quasi dieci.' },
  { italian: 'dieci', english: 'ten', category: 'numbers', difficulty: 'easy', hint: 'Le dita di due mani.' },
  { italian: 'zero', english: 'zero', category: 'numbers', difficulty: 'easy', hint: 'Nessuna quantità, il cerchio vuoto.' },
  { italian: 'undici', english: 'eleven', category: 'numbers', difficulty: 'medium', hint: 'Uno più di dieci.' },
  { italian: 'dodici', english: 'twelve', category: 'numbers', difficulty: 'medium', hint: 'Una dozzina.' },
  { italian: 'venti', english: 'twenty', category: 'numbers', difficulty: 'medium', hint: 'Dieci più dieci.' },
  { italian: 'trenta', english: 'thirty', category: 'numbers', difficulty: 'medium', hint: 'Tre volte dieci.' },
  { italian: 'cento', english: 'one hundred', category: 'numbers', difficulty: 'hard', hint: 'Un numero molto grande, 100.' },
  { italian: 'mille', english: 'one thousand', category: 'numbers', difficulty: 'hard', hint: 'Un numero grandissimo, 1000.' },

  // --- TIME (New) ---
  { italian: 'lunedi', english: 'Monday', category: 'time', difficulty: 'medium', hint: 'Il primo giorno della settimana.' },
  { italian: 'martedi', english: 'Tuesday', category: 'time', difficulty: 'medium', hint: 'Il secondo giorno della settimana.' },
  { italian: 'mercoledi', english: 'Wednesday', category: 'time', difficulty: 'medium', hint: 'Metà settimana.' },
  { italian: 'giovedi', english: 'Thursday', category: 'time', difficulty: 'medium', hint: 'Il giorno prima di venerdì.' },
  { italian: 'venerdi', english: 'Friday', category: 'time', difficulty: 'medium', hint: 'L\'ultimo giorno di scuola della settimana.' },
  { italian: 'sabato', english: 'Saturday', category: 'time', difficulty: 'medium', hint: 'Inizia il weekend!' },
  { italian: 'domenica', english: 'Sunday', category: 'time', difficulty: 'medium', hint: 'Il giorno di festa e riposo.' },
  { italian: 'oggi', english: 'today', category: 'time', difficulty: 'easy', hint: 'Il giorno in cui siamo adesso.' },
  { italian: 'domani', english: 'tomorrow', category: 'time', difficulty: 'easy', hint: 'Il giorno che arriverà dopo oggi.' },
  { italian: 'ieri', english: 'yesterday', category: 'time', difficulty: 'easy', hint: 'Il giorno che è già passato.' },
  { italian: 'mattina', english: 'morning', category: 'time', difficulty: 'medium', hint: 'Quando ti svegli e sorge il sole.' },
  { italian: 'sera', english: 'evening', category: 'time', difficulty: 'medium', hint: 'Quando il sole tramonta e si cena.' },
  { italian: 'notte', english: 'night', category: 'time', difficulty: 'easy', hint: 'Quando è buio e si dorme.' },
  { italian: 'gennaio', english: 'January', category: 'time', difficulty: 'hard', hint: 'Il primo mese dell\'anno.' },
  { italian: 'agosto', english: 'August', category: 'time', difficulty: 'hard', hint: 'Il mese più caldo dell\'estate.' },
  { italian: 'dicembre', english: 'December', category: 'time', difficulty: 'hard', hint: 'Il mese di Natale.' },

  // --- BODY (New) ---
  { italian: 'occhio', english: 'eye', category: 'body', difficulty: 'easy', hint: 'Ti serve per vedere.' },
  { italian: 'naso', english: 'nose', category: 'body', difficulty: 'easy', hint: 'Ti serve per annusare i profumi.' },
  { italian: 'bocca', english: 'mouth', category: 'body', difficulty: 'easy', hint: 'Ti serve per mangiare e parlare.' },
  { italian: 'orecchio', english: 'ear', category: 'body', difficulty: 'easy', hint: 'Ti serve per ascoltare i suoni.' },
  { italian: 'mano', english: 'hand', category: 'body', difficulty: 'easy', hint: 'Ha cinque dita e la usi per prendere le cose.' },
  { italian: 'piede', english: 'foot', category: 'body', difficulty: 'easy', hint: 'Ti serve per camminare e mettere le scarpe.' },
  { italian: 'testa', english: 'head', category: 'body', difficulty: 'easy', hint: 'La parte alta del corpo dove hai il cervello.' },
  { italian: 'pancia', english: 'tummy', category: 'body', difficulty: 'easy', hint: 'Brontola se hai fame.' },
  { italian: 'gamba', english: 'leg', category: 'body', difficulty: 'easy', hint: 'Ti sostiene e ti permette di correre.' },
  { italian: 'denti', english: 'teeth', category: 'body', difficulty: 'medium', hint: 'Sono bianchi, in bocca, e masticano il cibo.' },
  { italian: 'capelli', english: 'hair', category: 'body', difficulty: 'medium', hint: 'Crescono sulla testa.' },
  { italian: 'lingua', english: 'tongue', category: 'body', difficulty: 'medium', hint: 'È in bocca e ti fa sentire i sapori.' },
  { italian: 'braccio', english: 'arm', category: 'body', difficulty: 'medium', hint: 'Collega la mano alla spalla.' },
  { italian: 'cuore', english: 'heart', category: 'body', difficulty: 'medium', hint: 'Batte nel petto.' },
  { italian: 'ginocchio', english: 'knee', category: 'body', difficulty: 'hard', hint: 'Si piega a metà della gamba.' },
  { italian: 'gomito', english: 'elbow', category: 'body', difficulty: 'hard', hint: 'Si piega a metà del braccio.' },
  { italian: 'schiena', english: 'back', category: 'body', difficulty: 'hard', hint: 'La parte dietro del corpo.' },

  // --- EMOTIONS (New) ---
  { italian: 'felice', english: 'happy', category: 'emotions', difficulty: 'easy', hint: 'Quando sorridi e sei contento.' },
  { italian: 'triste', english: 'sad', category: 'emotions', difficulty: 'easy', hint: 'Quando piangi o non hai voglia di giocare.' },
  { italian: 'paura', english: 'fear', category: 'emotions', difficulty: 'easy', hint: 'Quando vedi un mostro o il buio.' },
  { italian: 'arrabbiato', english: 'angry', category: 'emotions', difficulty: 'medium', hint: 'Quando qualcosa non ti piace e ti infastidisci.' },
  { italian: 'stanco', english: 'tired', category: 'emotions', difficulty: 'medium', hint: 'Quando hai sonno e vuoi dormire.' },
  { italian: 'sorpresa', english: 'surprise', category: 'emotions', difficulty: 'medium', hint: 'Quando ricevi un regalo inaspettato.' },
  { italian: 'noia', english: 'boredom', category: 'emotions', difficulty: 'hard', hint: 'Quando non sai cosa fare.' },
  { italian: 'amore', english: 'love', category: 'emotions', difficulty: 'easy', hint: 'Volere molto bene a qualcuno.' },

  // --- WEATHER (New) ---
  { italian: 'pioggia', english: 'rain', category: 'weather', difficulty: 'easy', hint: 'Acqua che cade dal cielo.' },
  { italian: 'neve', english: 'snow', category: 'weather', difficulty: 'easy', hint: 'Fiocchi bianchi e freddi che cadono d\'inverno.' },
  { italian: 'vento', english: 'wind', category: 'weather', difficulty: 'easy', hint: 'Aria che si muove forte e sposta le foglie.' },
  { italian: 'nuvola', english: 'cloud', category: 'weather', difficulty: 'easy', hint: 'Batuffolo bianco nel cielo.' },
  { italian: 'caldo', english: 'hot', category: 'weather', difficulty: 'medium', hint: 'Quando c\'è tanto sole e sudi.' },
  { italian: 'freddo', english: 'cold', category: 'weather', difficulty: 'medium', hint: 'Quando devi mettere il cappotto.' },
  { italian: 'nebbia', english: 'fog', category: 'weather', difficulty: 'hard', hint: 'Nuvole basse che non ti fanno vedere bene.' },
  { italian: 'tempesta', english: 'storm', category: 'weather', difficulty: 'hard', hint: 'Pioggia forte con tuoni e fulmini.' },
  { italian: 'arcobaleno', english: 'rainbow', category: 'weather', difficulty: 'hard', hint: 'Arco colorato che esce dopo la pioggia.' },

  // --- CLOTHING (New) ---
  { italian: 'scarpe', english: 'shoes', category: 'clothing', difficulty: 'medium', hint: 'Si mettono ai piedi per uscire.' },
  { italian: 'calzini', english: 'socks', category: 'clothing', difficulty: 'medium', hint: 'Si mettono sotto le scarpe.' },
  { italian: 'maglietta', english: 't-shirt', category: 'clothing', difficulty: 'medium', hint: 'Si indossa sopra la pancia, a maniche corte.' },
  { italian: 'pantaloni', english: 'pants', category: 'clothing', difficulty: 'medium', hint: 'Coprono le gambe.' },
  { italian: 'cappello', english: 'hat', category: 'clothing', difficulty: 'easy', hint: 'Si mette in testa per il sole o il freddo.' },
  { italian: 'giacca', english: 'jacket', category: 'clothing', difficulty: 'medium', hint: 'Si mette quando fa freddo sopra i vestiti.' },
  { italian: 'vestito', english: 'dress', category: 'clothing', difficulty: 'medium', hint: 'Abito elegante intero.' },
  { italian: 'guanti', english: 'gloves', category: 'clothing', difficulty: 'hard', hint: 'Coprono le mani quando fa freddo.' },
  { italian: 'sciarpa', english: 'scarf', category: 'clothing', difficulty: 'hard', hint: 'Si mette al collo per stare al caldo.' },
  { italian: 'stivali', english: 'boots', category: 'clothing', difficulty: 'hard', hint: 'Scarpe alte per la pioggia o l\'inverno.' },

  // --- NATURE (New) ---
  { italian: 'albero', english: 'tree', category: 'nature', difficulty: 'easy', hint: 'Ha foglie, rami e un tronco.' },
  { italian: 'fiore', english: 'flower', category: 'nature', difficulty: 'easy', hint: 'Profumato e colorato, cresce nel prato.' },
  { italian: 'erba', english: 'grass', category: 'nature', difficulty: 'easy', hint: 'Verde e cresce per terra nel giardino.' },
  { italian: 'mare', english: 'sea', category: 'nature', difficulty: 'easy', hint: 'Tanta acqua salata blu.' },
  { italian: 'cielo', english: 'sky', category: 'nature', difficulty: 'easy', hint: 'È sopra di noi, azzurro di giorno.' },
  { italian: 'montagna', english: 'mountain', category: 'nature', difficulty: 'medium', hint: 'Molto alta, spesso ha la neve in cima.' },
  { italian: 'fiume', english: 'river', category: 'nature', difficulty: 'medium', hint: 'Acqua dolce che scorre verso il mare.' },
  { italian: 'lago', english: 'lake', category: 'nature', difficulty: 'medium', hint: 'Grande pozza d\'acqua dolce.' },
  { italian: 'bosco', english: 'forest', category: 'nature', difficulty: 'medium', hint: 'Tanti alberi insieme dove vivono gli animali.' },
  { italian: 'spiaggia', english: 'beach', category: 'nature', difficulty: 'medium', hint: 'Sabbia vicino al mare.' },
  { italian: 'sasso', english: 'stone', category: 'nature', difficulty: 'medium', hint: 'Pietra dura che trovi per terra.' },
  { italian: 'vulcano', english: 'volcano', category: 'nature', difficulty: 'hard', hint: 'Montagna che sputa fuoco e lava.' },
  { italian: 'deserto', english: 'desert', category: 'nature', difficulty: 'hard', hint: 'Posto con tanta sabbia e molto caldo.' },

  // --- TRANSPORT (New) ---
  { italian: 'auto', english: 'car', category: 'transport', difficulty: 'easy', hint: 'Ha quattro ruote e un motore.' },
  { italian: 'bici', english: 'bike', category: 'transport', difficulty: 'easy', hint: 'Ha due ruote e pedali.' },
  { italian: 'bus', english: 'bus', category: 'transport', difficulty: 'easy', hint: 'Grande mezzo per portare tante persone.' },
  { italian: 'treno', english: 'train', category: 'transport', difficulty: 'medium', hint: 'Viaggia sulle rotaie e fa ciuf ciuf.' },
  { italian: 'aereo', english: 'plane', category: 'transport', difficulty: 'medium', hint: 'Vola nel cielo e porta passeggeri.' },
  { italian: 'nave', english: 'ship', category: 'transport', difficulty: 'medium', hint: 'Galleggia e viaggia sul mare.' },
  { italian: 'moto', english: 'motorcycle', category: 'transport', difficulty: 'medium', hint: 'Come una bici ma con il motore veloce.' },
  { italian: 'camion', english: 'truck', category: 'transport', difficulty: 'hard', hint: 'Grande veicolo per trasportare merci.' },
  { italian: 'barca', english: 'boat', category: 'transport', difficulty: 'hard', hint: 'Piccolo mezzo per andare sull\'acqua.' },

  // --- SCHOOL (New) ---
  { italian: 'scuola', english: 'school', category: 'school', difficulty: 'medium', hint: 'Dove vai per imparare e vedere gli amici.' },
  { italian: 'penna', english: 'pen', category: 'school', difficulty: 'medium', hint: 'Si usa per scrivere con l\'inchiostro.' },
  { italian: 'gomma', english: 'eraser', category: 'school', difficulty: 'medium', hint: 'Cancella gli errori di matita.' },
  { italian: 'quaderno', english: 'notebook', category: 'school', difficulty: 'medium', hint: 'Ha pagine di carta per scrivere.' },
  { italian: 'banco', english: 'desk', category: 'school', difficulty: 'medium', hint: 'Il tavolo dove ti siedi a scuola.' },
  { italian: 'lavagna', english: 'blackboard', category: 'school', difficulty: 'medium', hint: 'La maestra ci scrive col gesso.' },
  { italian: 'classe', english: 'classroom', category: 'school', difficulty: 'medium', hint: 'La stanza dove stanno gli alunni.' },
  { italian: 'righello', english: 'ruler', category: 'school', difficulty: 'hard', hint: 'Serve per fare righe dritte e misurare.' },
  { italian: 'colla', english: 'glue', category: 'school', difficulty: 'hard', hint: 'Attacca i fogli di carta.' },
  { italian: 'forbici', english: 'scissors', category: 'school', difficulty: 'hard', hint: 'Servono per tagliare la carta.' }
];

export const ITALIAN_ALPHABET = 'abcdefghilmnopqrstuvz'.split('');
