
import { Word } from './types';

export const INITIAL_WORDS: Word[] = [
  { italian: 'gatto', english: 'cat', category: 'animals', difficulty: 'easy' },
  { italian: 'cane', english: 'dog', category: 'animals', difficulty: 'easy' },
  { italian: 'orso', english: 'bear', category: 'animals', difficulty: 'easy' },
  { italian: 'pesce', english: 'fish', category: 'animals', difficulty: 'easy' },
  { italian: 'luna', english: 'moon', category: 'objects', difficulty: 'easy' },
  { italian: 'sole', english: 'sun', category: 'objects', difficulty: 'easy' },
  { italian: 'casa', english: 'house', category: 'objects', difficulty: 'easy' },
  { italian: 'pane', english: 'bread', category: 'food', difficulty: 'easy' },
  { italian: 'latte', english: 'milk', category: 'food', difficulty: 'easy' },
  { italian: 'mela', english: 'apple', category: 'food', difficulty: 'easy' },
  { italian: 'rosso', english: 'red', category: 'colors', difficulty: 'easy' },
  { italian: 'blu', english: 'blue', category: 'colors', difficulty: 'easy' },
  { italian: 'mamma', english: 'mom', category: 'people', difficulty: 'easy' },
  { italian: 'papa', english: 'dad', category: 'people', difficulty: 'easy' },
  { italian: 'nonna', english: 'grandma', category: 'people', difficulty: 'easy' },
  { italian: 'nonno', english: 'grandpa', category: 'people', difficulty: 'easy' },
  { italian: 'farfalla', english: 'butterfly', category: 'animals', difficulty: 'medium' },
  { italian: 'coniglio', english: 'rabbit', category: 'animals', difficulty: 'medium' },
  { italian: 'tartaruga', english: 'turtle', category: 'animals', difficulty: 'medium' },
  { italian: 'giraffa', english: 'giraffe', category: 'animals', difficulty: 'medium' },
  { italian: 'elefante', english: 'elephant', category: 'animals', difficulty: 'medium' },
  { italian: 'scimmia', english: 'monkey', category: 'animals', difficulty: 'medium' },
  { italian: 'arancione', english: 'orange', category: 'colors', difficulty: 'medium' },
  { italian: 'giallo', english: 'yellow', category: 'colors', difficulty: 'medium' },
  { italian: 'verde', english: 'green', category: 'colors', difficulty: 'medium' },
  { italian: 'viola', english: 'purple', category: 'colors', difficulty: 'medium' },
  { italian: 'tavolo', english: 'table', category: 'objects', difficulty: 'medium' },
  { italian: 'sedia', english: 'chair', category: 'objects', difficulty: 'medium' },
  { italian: 'finestra', english: 'window', category: 'objects', difficulty: 'medium' },
  { italian: 'matita', english: 'pencil', category: 'objects', difficulty: 'medium' },
  { italian: 'libro', english: 'book', category: 'objects', difficulty: 'medium' },
  { italian: 'zaino', english: 'backpack', category: 'objects', difficulty: 'medium' },
  { italian: 'formaggio', english: 'cheese', category: 'food', difficulty: 'medium' },
  { italian: 'pomodoro', english: 'tomato', category: 'food', difficulty: 'medium' },
  { italian: 'banana', english: 'banana', category: 'food', difficulty: 'medium' },
  { italian: 'arancia', english: 'orange', category: 'food', difficulty: 'medium' },
  { italian: 'famiglia', english: 'family', category: 'people', difficulty: 'medium' },
  { italian: 'amico', english: 'friend', category: 'people', difficulty: 'medium' },
  { italian: 'maestra', english: 'teacher', category: 'people', difficulty: 'medium' },
  { italian: 'bambino', english: 'child', category: 'people', difficulty: 'medium' },
  { italian: 'correre', english: 'to run', category: 'verbs', difficulty: 'medium' },
  { italian: 'saltare', english: 'to jump', category: 'verbs', difficulty: 'medium' },
  { italian: 'mangiare', english: 'to eat', category: 'verbs', difficulty: 'medium' },
  { italian: 'bere', english: 'to drink', category: 'verbs', difficulty: 'easy' },
  { italian: 'coccodrillo', english: 'crocodile', category: 'animals', difficulty: 'hard' },
  { italian: 'ippopotamo', english: 'hippopotamus', category: 'animals', difficulty: 'hard' },
  { italian: 'pipistrello', english: 'bat', category: 'animals', difficulty: 'hard' },
  { italian: 'scoiattolo', english: 'squirrel', category: 'animals', difficulty: 'hard' },
  { italian: 'lucertola', english: 'lizard', category: 'animals', difficulty: 'hard' },
  { italian: 'rondine', english: 'swallow', category: 'animals', difficulty: 'hard' },
  { italian: 'meraviglia', english: 'wonder', category: 'objects', difficulty: 'hard' },
  { italian: 'avventura', english: 'adventure', category: 'objects', difficulty: 'hard' },
  { italian: 'cioccolato', english: 'chocolate', category: 'food', difficulty: 'hard' },
  { italian: 'fragola', english: 'strawberry', category: 'food', difficulty: 'hard' },
  { italian: 'melanzana', english: 'eggplant', category: 'food', difficulty: 'hard' },
  { italian: 'insegnante', english: 'teacher', category: 'people', difficulty: 'hard' },
  { italian: 'compagno', english: 'companion', category: 'people', difficulty: 'hard' },
  { italian: 'biblioteca', english: 'library', category: 'objects', difficulty: 'hard' },
  { italian: 'dinosauro', english: 'dinosaur', category: 'animals', difficulty: 'hard' },
  { italian: 'camminare', english: 'to walk', category: 'verbs', difficulty: 'hard' },
  { italian: 'raccontare', english: 'to tell', category: 'verbs', difficulty: 'hard' },
  { italian: 'disegnare', english: 'to draw', category: 'verbs', difficulty: 'hard' },
];

export const ITALIAN_ALPHABET = 'abcdefghilmnopqrstuvz'.split('');
